name: CI - Build And Push images to dockerhub

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/fyp-backend:latest

    - name: build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./careerhub
        file: ./careerhub/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/careerhub-project-frontend:latest
